# Environment that does not use a GPU
#  Installs packages needed for all features
name: mofa
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.*

  # Services used by the workflow
  - redis-server
  - mongodb

  # Tools to work with crystalline and molecular data
  - conda-forge::chargemol
  - conda-forge::raspa2
  - openbabel

  # Tools used for simulation
  - lammps
  - cp2k

  - pip
  - pip:
    - torch==2.1.0
    - numpy<2

    - -e ..[test]
